# Generated by Django 3.0.5 on 2020-05-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalproblems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='problem',
        ),
    ]
